version: '3.2'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - mysql-compose-network

  pgadmin-avenger:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mysql-compose-network

volumes:
  mdb:
networks:
  mysql-compose-network:
    driver: bridge
